# Generated by Django 6.0.2 on 2026-02-14 17:11

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_ref', models.CharField(db_index=True, max_length=120)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('trim', models.CharField(blank=True, default='', max_length=80)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(core.models.max_vehicle_year)])),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('dct', 'DCT'), ('other', 'Other')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG'), ('other', 'Other')], default='gasoline', max_length=20)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['owner_ref', 'created_at'], name='core_vehicl_owner_r_1fd205_idx'), models.Index(fields=['make', 'model', 'year'], name='core_vehicl_make_d97729_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('api', 'API'), ('whatsapp', 'WhatsApp'), ('web', 'Web')], default='api', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('needs_followup', 'Needs Follow-up'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=20)),
                ('current_risk_level', models.CharField(choices=[('unknown', 'Unknown'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='unknown', max_length=20)),
                ('initial_problem_title', models.CharField(blank=True, default='', max_length=200)),
                ('latest_user_message', models.TextField(blank=True, default='')),
                ('final_summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.vehicleprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('triage_level', models.CharField(choices=[('unknown', 'Unknown'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='unknown', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('likely_causes', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('stop_driving_reasons', models.JSONField(blank=True, default=list)),
                ('disclaimer_shown', models.BooleanField(default=True)),
                ('model_name', models.CharField(default='unknown', max_length=120)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_input', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_output', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.casesession')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'created_at'], name='core_diagno_case_id_313bfe_idx'), models.Index(fields=['triage_level', 'created_at'], name='core_diagno_triage__dc2a58_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'version'), name='uniq_case_version')],
            },
        ),
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], default='user', max_length=20)),
                ('raw_text', models.TextField()),
                ('normalized_symptoms', models.JSONField(blank=True, default=list)),
                ('observed_signals', models.JSONField(blank=True, default=dict)),
                ('odometer_at_report', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='core.casesession')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'created_at'], name='core_sympto_case_id_456cd5_idx'), models.Index(fields=['source', 'created_at'], name='core_sympto_source_574091_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='casesession',
            index=models.Index(fields=['status', 'current_risk_level', 'opened_at'], name='core_casese_status_db034b_idx'),
        ),
        migrations.AddIndex(
            model_name='casesession',
            index=models.Index(fields=['vehicle', 'last_activity_at'], name='core_casese_vehicle_d5f954_idx'),
        ),
    ]
