# Generated by Django 6.0.2 on 2026-02-15 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('save_note', 'Save Note'), ('create_checklist', 'Create Checklist'), ('escalate_case', 'Escalate Case'), ('resolve_case', 'Resolve Case')], max_length=40)),
                ('status', models.CharField(choices=[('executed', 'Executed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='executed', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.casesession')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'created_at'], name='core_caseac_case_id_b111be_idx'), models.Index(fields=['action_type', 'created_at'], name='core_caseac_action__ed7abf_idx'), models.Index(fields=['status', 'created_at'], name='core_caseac_status_6e3a5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('agent', 'Agent'), ('system', 'System')], default='agent', max_length=20)),
                ('note_text', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.casesession')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'created_at'], name='core_caseno_case_id_009d35_idx'), models.Index(fields=['source', 'created_at'], name='core_caseno_source_0b4a2e_idx')],
            },
        ),
    ]
