# Generated by Django 6.0.2 on 2026-02-14 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('owner_manual', 'Owner Manual'), ('service_guide', 'Service Guide'), ('trouble_code', 'Trouble Code Notes'), ('internal_note', 'Internal Note'), ('other', 'Other')], default='other', max_length=30)),
                ('vehicle_make', models.CharField(blank=True, default='', max_length=80)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=80)),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_docs/')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'is_active'], name='rag_knowled_source__8c18b7_idx'), models.Index(fields=['vehicle_make', 'vehicle_model'], name='rag_knowled_vehicle_904a5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('vector_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.knowledgedocument')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='rag_documen_documen_637082_idx'), models.Index(fields=['vector_id'], name='rag_documen_vector__29bdbd_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_doc_chunk_index')],
            },
        ),
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('top_k', models.PositiveIntegerField(default=5)),
                ('retrieved_chunks', models.JSONField(blank=True, default=list)),
                ('reranked', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to='core.casesession')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='rag_retriev_created_eba3cf_idx'), models.Index(fields=['top_k'], name='rag_retriev_top_k_0c9a99_idx')],
            },
        ),
    ]
